function main(argv)
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\targetpath.lua default")
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\target_rundir.lua default")
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\target_runenvs.lua default")
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\explorer.lua")
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\explorer.lua")
    os.exec("xmake check")
    os.exec("xmake check")
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\update_intellisense.lua .vscode clangd")
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\config.lua")
    os.exec("xmake check")
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\explorer.lua")
    os.exec("xmake check")
    os.exec("xmake check")
    os.exec("xmake ")
    os.exec("xmake ")
    os.exec("xmake ")
    os.exec("xmake ")
    os.exec("xmake ")
    os.exec("xmake l c:\\Users\\Clean\\.vscode\\extensions\\tboox.xmake-vscode-2.3.3\\assets\\explorer.lua")
    os.exec("xmake ")
    os.exec("xmake ")
end
